import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className='grid md:grid-cols-4 gap-4 mt-6'>
          <div className='bg-red-500 p-5 md:col-span-2 row-span-3'>1</div>
          <div className='bg-red-500 p-5'>2</div>
          <div className='bg-red-500 p-5'>3</div>
          <div className='bg-red-500 p-5'>4</div>
          <div className='bg-red-500 p-5'>5</div>
        </div>
      </main>
    </>
  )
}
